<%
out.println("<html>");
out.println("  <head>");
out.println("      <center>");
out.println("    <img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\logo.png\">");
out.println("      </center>");
out.println("    </div>");
out.println("</head>");
out.println("  <style>");
out.println("    img ");
out.println("    {");
out.println("      height: 50px;");
out.println("      weight: 50px;");
out.println("      }");
out.println("    head");
out.println("    { ");
out.println("      font-size: 30px; ");
out.println("    }");
out.println("    body {");
out.println("  background-image: url(\"https://dr5dymrsxhdzh.cloudfront.net/blog/images/a82fa497e/2019/04/financial-planning-picture-id611999050.jpg\");");
out.println("      background-size: cover;");
out.println("      background-position: center;");
out.println("  color: green;");
out.println("        font-size: 25px;");
out.println("}");
out.println("      h1 {");
out.println("  background-color: lavender;");
out.println("  color: green;");
out.println("}");
out.println("p {");
out.println("  background-color: lightgreen;");
out.println("  color: white;");
out.println("");
out.println("    }");
out.println("    a:hover {");
out.println("  color: red;");
out.println("} ");
out.println("    .sociallogo {");
out.println("      height:10px;");
out.println("      weight: 10px;");
out.println("    }");
out.println("  </style>");
out.println("    <body>");
out.println("      ");
out.println("      <marquee behavior=\"alternate\" direction=\"left\" width:30% height:50% >Join the investment revolution,one click at a time.</marquee> <br>");
out.println("      <p><center><b>What would you like to learn about/invest in today?</b><br>");
out.println("       <label for=\"page-select\">Select a Page:</label>");
out.println("  <select id=\"page-select\" onchange=\"goToPage()\">");
out.println("    <option value=\"\">Choose a page</option>");
out.println("    <option value=\"stocks.html\"> Stock Investments </option>");
out.println("    <option value=\"mutualfunds.html\"> Mutual Funds </option>");
out.println("    <option value=\"fds.html\">Fixed deposits (FDs) </option>");
out.println("      <option value = \"healthinsurance.html\"> Health Insurance </option>");
out.println("      <option value = \"terminsurance.html\"> Term Insurance </option>");
out.println("      <option value = \"bonds.html\"> Bonds </option>");
out.println("  </select><br><br>");
out.println("        <a href = \"calculator.html\"> Investment Calculator </a><br>");
out.println("        <a href = \"termsconditions.html\">Terms and Conditions </a><br>");
out.println("        <a href = \"aboutus.html\">About Us</a><br><br>");
out.println("        Help spread the word about our website!");
out.println("        <div class = \"sociallogo\">");
out.println("                  <a href = \"https://www.facebook.com/\"><img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\facebooklogo.png\"></a>");
out.println("         <a href = \"https://twitter.com/\"><img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\twitterlogo.jpeg\"></a>");
out.println("         <a href = \"https://www.linkedin.com/\"><img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\linkedinlogo (1).png\"></a>");
out.println("         <a href = \"https://www.reddit.com/\"><img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\redditlogo.png\"></a>");
out.println("       <a href = \"https://www.whatsapp.com/\"> <img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\whatsapplogo.png\"></a>                                                                                                                          ");
out.println("         <a href = \"mailto:sachinp@gmail.com\"> <img src = \"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\gmaillogo.png\"></a>");
out.println("                                                                                                                                     ");
out.println("                  </div>");
out.println("        </p>");
out.println("  <script type = \"text/javascript\">");
out.println("    function goToPage() {");
out.println("      var url = document.getElementById(\"page-select\").value;");
out.println("      if (url) {");
out.println("        window.location.href = url;");
out.println("      }");
out.println("    }");
out.println("    navigator.share({title: InsureGrow, url: new URL(\"C:\\Users\\User\\Desktop\\microinvestment\\microinvestment 2\\microinv1.html\").href, text: 'Welcome to InsureGrow'});");
out.println("  </script>");
out.println("      </center>");
out.println("      </p>");
out.println("      </h1> <br><br>");
out.println("</body>");
out.println("</html>");
%>
